---
title: "Amrit Patel's CV"
author: Amrit Patel
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1Y2d8cl3_1zQ5-CzmKtn47VlLdQUYCqY2KfrMMWwn97g",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data %>% dplyr::filter(section != "training"))
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _amritpatel.rbind.io/about/cv.html_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/amritpatel/adpatelCV/raw/master/adpatel_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/amritpatel/adpatelCV](https://github.com/amritpatel/adpatelCV).

Last updated on `r Sys.Date()`.



Main
================================================================================

Amrit Patel {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

<!-- ::: aside
```{r}
CV %<>% print_text_block('work_experience_aside')
```
::: -->

```{r}
CV %<>% print_section('industry_positions')
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

<!-- ::: aside
```{r}
CV %<>% print_text_block('research_experience_aside')
```
::: -->

```{r}
CV %<>% print_section('research_positions')
```



Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```



Selected Data Science Writing {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('data_science_writings')
```



Work-Related Training {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('training')
```



Selected Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



```{r}
CV %<>% print_links()
```

